import type { Metadata } from 'next';
import { MEDIA_ASSETS, MEDIA_GROUPS } from '@/content/media/manifest';
import { Badge, Card, Callout } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Media library and attribution',
  description:
    'Every image, video and audio clip used in HTML Hero, with its source, creator, licence and local path.',
};

/**
 * The media attribution page.
 *
 * Every asset the platform ships is listed here with its provenance, as
 * promised in the course. All of it was generated by this repository's own
 * code and released under CC0-1.0, which means learners may use any of it in
 * their own projects with no obligation.
 */
export default function MediaPage() {
  return (
    <div className="max-w-5xl p-5 lg:p-10">
      <header className="mb-7">
        <h1 className="text-2xl font-bold text-ink lg:text-3xl">Media library and attribution</h1>
        <p className="mt-2 max-w-3xl text-muted">
          {MEDIA_ASSETS.length} assets, all stored locally in{' '}
          <code className="rounded bg-[hsl(var(--bg-subtle))] px-1.5 py-0.5 font-mono text-sm">
            public/learning-media
          </code>
          . Nothing here is hotlinked, and nothing is downloaded at build or run time — every
          example in every lesson works offline.
        </p>
      </header>

      <Callout tone="tip" title="You may use any of this in your own work">
        <p>
          Every asset was created from scratch by this project&rsquo;s own generator script and
          released under{' '}
          <a
            href="https://creativecommons.org/publicdomain/zero/1.0/"
            rel="noopener noreferrer"
            target="_blank"
          >
            CC0-1.0
          </a>{' '}
          — a public-domain dedication. You can use, modify and redistribute any of it, including
          commercially, with no attribution required. Attribution is welcome but never obligatory.
        </p>
      </Callout>

      <Callout tone="note" title="How this library was built">
        <p>
          The raster scenes are rendered procedurally with Pillow; the diagrams and icons are
          hand-authored SVG; the videos are encoded from generated frames with ffmpeg; the audio is
          synthesised from mathematical expressions. None of it is a photograph of a real place or
          person, and none of it derives from a third-party work — which is what makes the licence
          position unambiguous.
        </p>
      </Callout>

      {MEDIA_GROUPS.map((group) => {
        const assets = MEDIA_ASSETS.filter((asset) => group.slugs.includes(asset.slug));
        if (assets.length === 0) return null;

        return (
          <section key={group.id} className="mt-9" aria-labelledby={`group-${group.id}`}>
            <h2 id={`group-${group.id}`} className="mb-4 text-xl font-bold text-ink">
              {group.label}
              <span className="ml-2 text-sm font-normal text-muted">({assets.length})</span>
            </h2>

            <ul className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {assets.map((asset) => (
                <li key={asset.slug}>
                  <Card className="h-full overflow-hidden">
                    <div className="aspect-[4/3] grid place-items-center overflow-hidden bg-[hsl(var(--bg-subtle))]">
                      {asset.kind === 'video' ? (
                        /* eslint-disable-next-line @next/next/no-img-element */
                        <img
                          src={asset.posterPath ?? asset.path}
                          alt={asset.suggestedAlt}
                          className="h-full w-full object-cover"
                          loading="lazy"
                        />
                      ) : asset.kind === 'audio' ? (
                        <span className="px-4 text-center text-sm text-muted">
                          Audio · {asset.durationSeconds}s
                        </span>
                      ) : (
                        /* eslint-disable-next-line @next/next/no-img-element */
                        <img
                          src={asset.path}
                          alt={asset.suggestedAlt}
                          className={
                            asset.kind === 'icon'
                              ? 'h-full w-full object-contain p-10'
                              : 'h-full w-full object-cover'
                          }
                          loading="lazy"
                        />
                      )}
                    </div>

                    <div className="p-4">
                      <h3 className="font-semibold text-ink">{asset.title}</h3>
                      <p className="mt-1 text-sm text-muted">{asset.description}</p>

                      <dl className="mt-3 space-y-1.5 text-xs">
                        <Row term="Creator" value={asset.attribution.creator} />
                        <Row term="Source" value={asset.attribution.source} />
                        <Row term="Licence" value={asset.attribution.licence} />
                        <Row term="Local path" value={asset.attribution.localPath} mono />
                        <Row term="Retrieved" value={asset.attribution.retrievedOn} />
                        {asset.attribution.notes ? (
                          <Row term="Notes" value={asset.attribution.notes} />
                        ) : null}
                      </dl>

                      {asset.suggestedAlt ? (
                        <p className="mt-3 rounded-lg bg-[hsl(var(--bg-subtle))] p-2.5 text-xs text-muted">
                          <strong className="font-semibold text-ink">Suggested alt text:</strong>{' '}
                          {asset.suggestedAlt}
                        </p>
                      ) : (
                        <p className="mt-3 rounded-lg bg-[hsl(var(--bg-subtle))] p-2.5 text-xs text-muted">
                          <strong className="font-semibold text-ink">Decorative:</strong> use{' '}
                          <code>alt=&quot;&quot;</code> so screen readers skip it.
                        </p>
                      )}

                      <div className="mt-3 flex flex-wrap gap-1.5">
                        {asset.tags.slice(0, 4).map((tag) => (
                          <Badge key={tag}>{tag}</Badge>
                        ))}
                      </div>
                    </div>
                  </Card>
                </li>
              ))}
            </ul>
          </section>
        );
      })}
    </div>
  );
}

function Row({ term, value, mono }: { term: string; value: string; mono?: boolean }) {
  return (
    <div className="flex gap-2">
      <dt className="shrink-0 font-semibold text-ink">{term}:</dt>
      <dd className={mono ? 'break-all font-mono text-muted' : 'text-muted'}>{value}</dd>
    </div>
  );
}
