/**
 * The learning media library.
 *
 * Every asset listed here was created from scratch by `scripts/generate_media.py`
 * in this repository. Nothing is downloaded at build or run time, nothing is
 * hotlinked, and no third-party work is included. All assets are dedicated to
 * the public domain under CC0-1.0, which is recorded per-asset below and
 * surfaced to learners on the in-app `/media` page.
 *
 * `npm run media:verify` walks this file and fails the build if any path,
 * srcset entry, poster or captions file is missing from `public/`.
 */

import type { MediaKind } from '@/lib/supabase/database.types';

export interface MediaSource {
  /** Public path, always beginning `/learning-media/`. */
  path: string;
  /** MIME type, used for `<source type="…">` in lessons. */
  type: string;
  width?: number;
  height?: number;
}

export interface MediaAttribution {
  assetTitle: string;
  creator: string;
  source: string;
  sourceUrl: string | null;
  licence: string;
  licenceUrl: string | null;
  attributionText: string;
  localPath: string;
  retrievedOn: string;
  notes?: string;
}

export interface MediaAsset {
  slug: string;
  kind: MediaKind;
  title: string;
  description: string;
  /** The path used in a plain `src`, guaranteed to exist. */
  path: string;
  width?: number;
  height?: number;
  durationSeconds?: number;
  /** Responsive candidates, widest last. */
  srcset: MediaSource[];
  /** Alternative encodings for `<picture>` / `<video>` / `<audio>`. */
  formats: MediaSource[];
  posterPath?: string;
  captionsPath?: string;
  /** A model answer for `alt`, used in lessons and the media picker. */
  suggestedAlt: string;
  /** True when the asset is the course's example of a *decorative* image. */
  isDecorativeExample: boolean;
  tags: string[];
  attribution: MediaAttribution;
}

const RETRIEVED = '2026-07-27';

function cc0(assetTitle: string, localPath: string, notes?: string): MediaAttribution {
  return {
    assetTitle,
    creator: 'HTML Hero (generated by scripts/generate_media.py)',
    source: 'Created for this project',
    sourceUrl: null,
    licence: 'CC0-1.0 (public domain dedication)',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attributionText:
      'Original artwork created for HTML Hero and released under CC0-1.0. ' +
      'No attribution is required, but it is welcome.',
    localPath,
    retrievedOn: RETRIEVED,
    ...(notes ? { notes } : {}),
  };
}

/** Widths emitted for every raster scene by the generator. */
const WIDTHS = [480, 800, 1200, 1600] as const;

interface SceneSpec {
  slug: string;
  title: string;
  description: string;
  suggestedAlt: string;
  tags: string[];
  aspect: 'landscape' | 'portrait' | 'square';
  decorative?: boolean;
}

const SCENES: SceneSpec[] = [
  {
    slug: 'coast-sunrise',
    title: 'Sunrise over a quiet coast',
    description:
      'A wide landscape scene: layered headlands behind a calm sea, with the rising sun laying a glittering path across the water.',
    suggestedAlt: 'Sunrise over a calm sea, with low headlands silhouetted against an orange sky',
    tags: ['landscape', 'nature', 'hero', 'travel'],
    aspect: 'landscape',
  },
  {
    slug: 'forest-path',
    title: 'Path through a bright forest',
    description: 'A sandy path leading between tall trees, with shafts of light coming through the canopy.',
    suggestedAlt: 'A narrow sandy path winding between tall trees in a sunlit forest',
    tags: ['landscape', 'nature', 'hobby', 'outdoors'],
    aspect: 'landscape',
  },
  {
    slug: 'city-dusk',
    title: 'City skyline at dusk',
    description: 'A layered skyline of lit windows against a violet evening sky.',
    suggestedAlt: 'A city skyline at dusk with hundreds of lit office windows',
    tags: ['landscape', 'city', 'hero', 'news'],
    aspect: 'landscape',
  },
  {
    slug: 'studio-desk',
    title: 'A tidy studio desk',
    description: 'An open laptop, a notebook and a mug on a wooden desk in soft daylight — a calm working scene.',
    suggestedAlt: 'An open laptop, a notebook and a coffee mug on a wooden desk',
    tags: ['business', 'about', 'workspace', 'portfolio'],
    aspect: 'landscape',
  },
  {
    slug: 'team-portrait',
    title: 'Portrait of a team member',
    description: 'A stylised head-and-shoulders portrait on a blue background, for "meet the team" examples.',
    suggestedAlt: 'A head-and-shoulders portrait of a person in a dark jacket against a blue background',
    tags: ['portrait', 'people', 'about', 'team'],
    aspect: 'portrait',
  },
  {
    slug: 'product-bottle',
    title: 'Product shot: ceramic bottle',
    description: 'A green ceramic bottle with a cork stopper on a plain studio backdrop.',
    suggestedAlt: 'A dark green ceramic bottle with a cork stopper, photographed on a plain grey background',
    tags: ['product', 'shop', 'square', 'business'],
    aspect: 'square',
  },
  {
    slug: 'workshop-tools',
    title: 'A workshop wall of tools',
    description: 'Hand tools hanging in neat rows above a workbench — for local-service and trade examples.',
    suggestedAlt: 'Hand tools hanging in rows on a workshop wall above a wooden workbench',
    tags: ['service', 'business', 'trade'],
    aspect: 'landscape',
  },
  {
    slug: 'restaurant-plate',
    title: 'A plated dish, from above',
    description: 'An overhead view of a garnished dish on a white plate against a dark table.',
    suggestedAlt: 'An overhead view of a colourful plated dish on a white plate',
    tags: ['restaurant', 'food', 'menu'],
    aspect: 'landscape',
  },
  {
    slug: 'event-stage',
    title: 'A lit stage and audience',
    description: 'Coloured stage lights above a crowd, seen from the back of a venue.',
    suggestedAlt: 'A crowd silhouetted in front of a stage lit by pink and blue lights',
    tags: ['event', 'music', 'hero'],
    aspect: 'landscape',
  },
  {
    slug: 'vehicle-hire',
    title: 'A hire car on an open road',
    description: 'A blue car in side profile on a road under a clear sky.',
    suggestedAlt: 'A blue five-door car photographed side-on, parked on an open road',
    tags: ['vehicle', 'rental', 'product'],
    aspect: 'landscape',
  },
  {
    slug: 'newsroom-desk',
    title: 'Scattered newspaper pages',
    description: 'Overlapping newspaper layouts, used for magazine and news-style examples.',
    suggestedAlt: 'Several overlapping newspaper pages spread across a desk',
    tags: ['news', 'magazine', 'editorial'],
    aspect: 'landscape',
  },
];

function sceneAsset(spec: SceneSpec): MediaAsset {
  const heightFor = (w: number) =>
    spec.aspect === 'landscape'
      ? Math.round((w * 1067) / 1600)
      : spec.aspect === 'portrait'
        ? Math.round((w * 1600) / 1067)
        : w;

  const srcset: MediaSource[] = WIDTHS.map((w) => ({
    path: `/learning-media/images/${spec.slug}-${w}.jpg`,
    type: 'image/jpeg',
    width: w,
    height: heightFor(w),
  }));

  const formats: MediaSource[] = WIDTHS.map((w) => ({
    path: `/learning-media/images/${spec.slug}-${w}.webp`,
    type: 'image/webp',
    width: w,
    height: heightFor(w),
  }));

  return {
    slug: spec.slug,
    kind: 'photo',
    title: spec.title,
    description: spec.description,
    path: `/learning-media/images/${spec.slug}.jpg`,
    width: 1200,
    height: heightFor(1200),
    srcset,
    formats,
    suggestedAlt: spec.suggestedAlt,
    isDecorativeExample: spec.decorative ?? false,
    tags: spec.tags,
    attribution: cc0(spec.title, `/learning-media/images/${spec.slug}.jpg`,
      'Rendered procedurally from code; not a photograph of a real place or person.'),
  };
}

interface DiagramSpec {
  slug: string;
  title: string;
  description: string;
  suggestedAlt: string;
  tags: string[];
  decorative?: boolean;
}

const DIAGRAMS: DiagramSpec[] = [
  {
    slug: 'how-the-web-works',
    title: 'How a page reaches your screen',
    description: 'A browser asking a server for a page, and the server sending HTML back.',
    suggestedAlt: 'A browser window requesting a page from a server, which returns an HTML file',
    tags: ['diagram', 'foundations'],
  },
  {
    slug: 'document-tree',
    title: 'The document tree',
    description: 'An HTML document drawn as a tree: html at the top, branching into head and body.',
    suggestedAlt: 'A tree diagram with html at the top branching into head and body, which branch into title, meta, h1 and p',
    tags: ['diagram', 'structure', 'dom'],
  },
  {
    slug: 'anatomy-of-an-element',
    title: 'Anatomy of an element',
    description: 'A labelled link showing the opening tag, attribute, content and closing tag.',
    suggestedAlt: 'A link element labelled to show its opening tag, href attribute, text content and closing tag',
    tags: ['diagram', 'syntax'],
  },
  {
    slug: 'heading-hierarchy',
    title: 'Heading hierarchy',
    description: 'Headings drawn as an indented outline from h1 down to h3.',
    suggestedAlt: 'An indented outline showing one h1, then h2 sections, each containing h3 subsections',
    tags: ['diagram', 'text'],
  },
  {
    slug: 'semantic-landmarks',
    title: 'Page landmarks',
    description: 'A page layout diagram labelling header, nav, main, article, aside and footer.',
    suggestedAlt: 'A page layout with labelled regions: header, nav, main containing an article, an aside, and a footer',
    tags: ['diagram', 'semantics'],
  },
  {
    slug: 'responsive-images',
    title: 'One image, several sizes',
    description: 'The same image served at three widths to a phone, a tablet and a desktop.',
    suggestedAlt: 'A phone, tablet and desktop screen each showing the same image at a different size',
    tags: ['diagram', 'images', 'responsive'],
  },
  {
    slug: 'form-anatomy',
    title: 'How a label finds its input',
    description: 'A label and input joined by matching for and id values.',
    suggestedAlt: 'A label element with for="email" connected by an arrow to an input with id="email"',
    tags: ['diagram', 'forms', 'accessibility'],
  },
  {
    slug: 'file-paths',
    title: 'Relative paths in a project',
    description: 'A folder tree with worked examples of relative paths from two different pages.',
    suggestedAlt: 'A folder tree showing index.html, an images folder and a projects folder, with example relative paths',
    tags: ['diagram', 'paths', 'architecture'],
  },
  {
    slug: 'table-structure',
    title: 'The parts of a data table',
    description: 'A table diagram labelling caption, thead, th scope values, tbody and tfoot.',
    suggestedAlt: 'A table diagram labelling the caption, header row of th cells, body rows of td cells and a footer row',
    tags: ['diagram', 'tables'],
  },
  {
    slug: 'accessibility-tree',
    title: 'From HTML to the accessibility tree',
    description: 'How semantic HTML becomes the structure assistive technology reads aloud.',
    suggestedAlt: 'HTML elements on the left mapping to accessibility roles in the middle, read by a screen reader on the right',
    tags: ['diagram', 'accessibility', 'aria'],
  },
  {
    slug: 'placeholder',
    title: 'Neutral placeholder graphic',
    description:
      'A plain grey placeholder. Used in lessons that teach *decorative* images, where alt="" is the correct answer.',
    suggestedAlt: '',
    tags: ['decorative', 'placeholder'],
    decorative: true,
  },
];

function diagramAsset(spec: DiagramSpec): MediaAsset {
  const path = `/learning-media/svg/${spec.slug}.svg`;
  return {
    slug: spec.slug,
    kind: 'illustration',
    title: spec.title,
    description: spec.description,
    path,
    srcset: [],
    formats: [{ path, type: 'image/svg+xml' }],
    suggestedAlt: spec.suggestedAlt,
    isDecorativeExample: spec.decorative ?? false,
    tags: spec.tags,
    attribution: cc0(spec.title, path, 'Hand-authored SVG markup, written for this course.'),
  };
}

const ICON_SLUGS = [
  'home', 'mail', 'phone', 'map-pin', 'clock', 'star',
  'check', 'search', 'menu', 'download', 'play', 'calendar',
] as const;

function iconAsset(slug: string): MediaAsset {
  const path = `/learning-media/icons/${slug}.svg`;
  const name = slug.replace(/-/g, ' ');
  return {
    slug: `icon-${slug}`,
    kind: 'icon',
    title: `${name.charAt(0).toUpperCase()}${name.slice(1)} icon`,
    description: `A simple line icon of a ${name}, drawn on a 24 by 24 grid.`,
    path,
    width: 24,
    height: 24,
    srcset: [],
    formats: [{ path, type: 'image/svg+xml' }],
    // Icons that sit beside a text label are decorative and take alt="".
    suggestedAlt: '',
    isDecorativeExample: true,
    tags: ['icon', 'ui', slug],
    attribution: cc0(`${name} icon`, path, 'Hand-authored SVG path data.'),
  };
}

const VIDEOS: MediaAsset[] = [
  {
    slug: 'page-anatomy',
    kind: 'video',
    title: 'How an HTML page is built',
    description:
      'A 10-second explainer: a document is typed out tag by tag while the browser preview assembles alongside it.',
    path: '/learning-media/video/page-anatomy.mp4',
    width: 1280,
    height: 720,
    durationSeconds: 10,
    srcset: [],
    formats: [
      { path: '/learning-media/video/page-anatomy.webm', type: 'video/webm', width: 1280, height: 720 },
      { path: '/learning-media/video/page-anatomy.mp4', type: 'video/mp4', width: 1280, height: 720 },
    ],
    posterPath: '/learning-media/posters/page-anatomy.jpg',
    captionsPath: '/learning-media/captions/page-anatomy.en.vtt',
    suggestedAlt: 'A short animation showing HTML being typed and the resulting page appearing',
    isDecorativeExample: false,
    tags: ['video', 'foundations', 'explainer'],
    attribution: cc0('How an HTML page is built', '/learning-media/video/page-anatomy.mp4',
      'Frames rendered with Pillow and encoded with ffmpeg by this repository.'),
  },
  {
    slug: 'responsive-layout',
    kind: 'video',
    title: 'One page, every screen size',
    description: 'An 11-second explainer showing a card layout reflowing as the viewport narrows.',
    path: '/learning-media/video/responsive-layout.mp4',
    width: 1280,
    height: 720,
    durationSeconds: 11,
    srcset: [],
    formats: [
      { path: '/learning-media/video/responsive-layout.webm', type: 'video/webm', width: 1280, height: 720 },
      { path: '/learning-media/video/responsive-layout.mp4', type: 'video/mp4', width: 1280, height: 720 },
    ],
    posterPath: '/learning-media/posters/responsive-layout.jpg',
    captionsPath: '/learning-media/captions/responsive-layout.en.vtt',
    suggestedAlt: 'A short animation of a page layout changing from three columns to one as the window narrows',
    isDecorativeExample: false,
    tags: ['video', 'responsive', 'explainer'],
    attribution: cc0('One page, every screen size', '/learning-media/video/responsive-layout.mp4',
      'Frames rendered with Pillow and encoded with ffmpeg by this repository.'),
  },
];

const AUDIO: MediaAsset[] = [
  {
    slug: 'welcome-chime',
    kind: 'audio',
    title: 'Welcome chime',
    description: 'A three-second bell chime, synthesised from a major triad. Useful for short <audio> examples.',
    path: '/learning-media/audio/welcome-chime.mp3',
    durationSeconds: 3,
    srcset: [],
    formats: [
      { path: '/learning-media/audio/welcome-chime.mp3', type: 'audio/mpeg' },
      { path: '/learning-media/audio/welcome-chime.wav', type: 'audio/wav' },
    ],
    suggestedAlt: '',
    isDecorativeExample: false,
    tags: ['audio', 'ui', 'short'],
    attribution: cc0('Welcome chime', '/learning-media/audio/welcome-chime.mp3',
      'Synthesised from a mathematical expression; contains no recorded material.'),
  },
  {
    slug: 'calm-loop',
    kind: 'audio',
    title: 'Calm ambient loop',
    description: 'An eight-second ambient tone that loops cleanly. Useful for demonstrating <audio> controls.',
    path: '/learning-media/audio/calm-loop.mp3',
    durationSeconds: 8,
    srcset: [],
    formats: [
      { path: '/learning-media/audio/calm-loop.mp3', type: 'audio/mpeg' },
      { path: '/learning-media/audio/calm-loop.wav', type: 'audio/wav' },
    ],
    suggestedAlt: '',
    isDecorativeExample: false,
    tags: ['audio', 'ambient', 'loop'],
    attribution: cc0('Calm ambient loop', '/learning-media/audio/calm-loop.mp3',
      'Synthesised from a mathematical expression; contains no recorded material.'),
  },
];

export const MEDIA_ASSETS: MediaAsset[] = [
  ...SCENES.map(sceneAsset),
  ...DIAGRAMS.map(diagramAsset),
  ...ICON_SLUGS.map(iconAsset),
  ...VIDEOS,
  ...AUDIO,
];

export const MEDIA_BY_SLUG: ReadonlyMap<string, MediaAsset> = new Map(
  MEDIA_ASSETS.map((asset) => [asset.slug, asset]),
);

export function getMedia(slug: string): MediaAsset | undefined {
  return MEDIA_BY_SLUG.get(slug);
}

/**
 * Every public path this library owns, including responsive variants, posters
 * and caption files. `verify-media.mjs` checks each one exists on disk, and the
 * evaluator uses it to tell a learner when a media path is broken.
 */
export function allMediaPaths(): string[] {
  const paths = new Set<string>();
  for (const asset of MEDIA_ASSETS) {
    paths.add(asset.path);
    for (const s of asset.srcset) paths.add(s.path);
    for (const f of asset.formats) paths.add(f.path);
    if (asset.posterPath) paths.add(asset.posterPath);
    if (asset.captionsPath) paths.add(asset.captionsPath);
  }
  paths.add('/learning-media/favicon.svg');
  paths.add('/learning-media/favicon.png');
  return [...paths].sort();
}

/** A curated shortlist for the editor's media picker, grouped for browsing. */
export const MEDIA_GROUPS: { id: string; label: string; slugs: string[] }[] = [
  { id: 'photos', label: 'Photographs & scenes', slugs: SCENES.map((s) => s.slug) },
  { id: 'diagrams', label: 'Diagrams & illustrations', slugs: DIAGRAMS.map((d) => d.slug) },
  { id: 'icons', label: 'Icons', slugs: ICON_SLUGS.map((s) => `icon-${s}`) },
  { id: 'video', label: 'Video', slugs: VIDEOS.map((v) => v.slug) },
  { id: 'audio', label: 'Audio', slugs: AUDIO.map((a) => a.slug) },
];
