import type { AchievementSpec } from './types';

/**
 * Achievements.
 *
 * Each criteria object is evaluated by `src/lib/progress/achievements.ts`.
 * Because they are stored as data, a new achievement is a new row — no code
 * change is needed for anything the evaluator already understands.
 *
 * Tone matters here: these mark genuine learning milestones, not participation.
 * There is deliberately no achievement for "logged in" or "clicked something".
 */
export const ACHIEVEMENTS: AchievementSpec[] = [
  {
    slug: 'first-html-page',
    name: 'First HTML Page',
    description: 'You wrote a complete, valid HTML document from an empty file.',
    icon: 'star',
    tier: 'bronze',
    criteria: { type: 'module_completed', moduleSlug: 'the-html-skeleton' },
    xp: 60,
  },
  {
    slug: 'document-architect',
    name: 'Document Architect',
    description: 'You mastered document structure — doctype, head, body and metadata.',
    icon: 'home',
    tier: 'bronze',
    criteria: { type: 'skill_mastered', skillSlug: 'document-structure' },
    xp: 80,
  },
  {
    slug: 'wordsmith',
    name: 'Wordsmith',
    description: 'You mastered text semantics: the right element for every kind of content.',
    icon: 'check',
    tier: 'bronze',
    criteria: { type: 'skill_mastered', skillSlug: 'text-semantics' },
    xp: 80,
  },
  {
    slug: 'navigation-builder',
    name: 'Navigation Builder',
    description: 'You connected a multi-page site with consistent, accessible navigation.',
    icon: 'map-pin',
    tier: 'silver',
    criteria: { type: 'level_completed', levelSlug: 'navigation-architect' },
    xp: 120,
  },
  {
    slug: 'media-specialist',
    name: 'Media Specialist',
    description: 'You built a media-rich page with accessible video and correct fallbacks.',
    icon: 'play',
    tier: 'silver',
    criteria: { type: 'level_completed', levelSlug: 'media-specialist' },
    xp: 120,
  },
  {
    slug: 'responsive-image-expert',
    name: 'Responsive Image Expert',
    description: 'You mastered srcset, sizes and picture — the right image for every screen.',
    icon: 'search',
    tier: 'silver',
    criteria: { type: 'skill_mastered', skillSlug: 'responsive-images' },
    xp: 120,
  },
  {
    slug: 'semantic-professional',
    name: 'Semantic HTML Professional',
    description: 'You mastered semantic structure and landmarks.',
    icon: 'menu',
    tier: 'silver',
    criteria: { type: 'skill_mastered', skillSlug: 'semantic-html' },
    xp: 140,
  },
  {
    slug: 'form-engineer',
    name: 'Form Engineer',
    description: 'You built a professional, accessible form with real validation.',
    icon: 'mail',
    tier: 'silver',
    criteria: { type: 'skill_mastered', skillSlug: 'forms' },
    xp: 140,
  },
  {
    slug: 'table-craftsman',
    name: 'Table Craftsman',
    description: 'You built data tables a screen-reader user can actually navigate.',
    icon: 'calendar',
    tier: 'silver',
    criteria: { type: 'skill_mastered', skillSlug: 'tables' },
    xp: 120,
  },
  {
    slug: 'no-javascript-needed',
    name: 'No JavaScript Needed',
    description: 'You built interactive features using nothing but HTML.',
    icon: 'check',
    tier: 'silver',
    criteria: { type: 'level_completed', levelSlug: 'native-interaction' },
    xp: 140,
  },
  {
    slug: 'accessibility-champion',
    name: 'Accessibility Champion',
    description: 'You audited and repaired an inaccessible site, and mastered accessible HTML.',
    icon: 'star',
    tier: 'gold',
    criteria: { type: 'skill_mastered', skillSlug: 'accessibility' },
    xp: 200,
  },
  {
    slug: 'metadata-master',
    name: 'Metadata Master',
    description: 'You mastered titles, descriptions, social metadata and structured data.',
    icon: 'search',
    tier: 'gold',
    criteria: { type: 'level_completed', levelSlug: 'metadata-and-seo' },
    xp: 180,
  },
  {
    slug: 'debugging-detective',
    name: 'Debugging Detective',
    description: 'You repaired ten debugging challenges.',
    icon: 'search',
    tier: 'gold',
    criteria: { type: 'debug_challenges', count: 10 },
    xp: 180,
  },
  {
    slug: 'validation-expert',
    name: 'Validation Expert',
    description: 'You mastered validation — invalid markup no longer gets past you.',
    icon: 'check',
    tier: 'gold',
    criteria: { type: 'skill_mastered', skillSlug: 'validation' },
    xp: 180,
  },
  {
    slug: 'multi-page-builder',
    name: 'Multi-Page Builder',
    description: 'Your capstone site reached five complete pages.',
    icon: 'home',
    tier: 'gold',
    criteria: { type: 'project_pages', count: 5 },
    xp: 200,
  },
  {
    slug: 'first-pass',
    name: 'Clean First Attempt',
    description: 'You passed five exercises in a row first time, with no hints.',
    icon: 'star',
    tier: 'silver',
    criteria: { type: 'first_pass_streak', count: 5 },
    xp: 120,
  },
  {
    slug: 'steady-week',
    name: 'Steady Week',
    description: 'You studied on seven consecutive days.',
    icon: 'calendar',
    tier: 'bronze',
    criteria: { type: 'streak_days', days: 7 },
    xp: 80,
  },
  {
    slug: 'three-week-habit',
    name: 'Three-Week Habit',
    description: 'A twenty-one day streak. This is what learning to code actually looks like.',
    icon: 'calendar',
    tier: 'gold',
    criteria: { type: 'streak_days', days: 21 },
    xp: 220,
  },
  {
    slug: 'half-way',
    name: 'Half Way',
    description: 'You completed thirty lessons.',
    icon: 'clock',
    tier: 'silver',
    criteria: { type: 'lessons_completed', count: 30 },
    xp: 140,
  },
  {
    slug: 'practice-makes-permanent',
    name: 'Practice Makes Permanent',
    description: 'You passed fifty coding exercises.',
    icon: 'check',
    tier: 'gold',
    criteria: { type: 'exercises_passed', count: 50 },
    xp: 200,
  },
  {
    slug: 'well-rounded',
    name: 'Well Rounded',
    description: 'You mastered fifteen separate skills.',
    icon: 'star',
    tier: 'gold',
    criteria: { type: 'skills_mastered', count: 15 },
    xp: 240,
  },
  {
    slug: 'html-hero',
    name: 'HTML Hero',
    description:
      'You completed the entire course and shipped a professional multi-page website. This is the one that matters.',
    icon: 'star',
    tier: 'platinum',
    criteria: { type: 'course_complete' },
    xp: 800,
  },
];
