#!/usr/bin/env tsx
/**
 * Writes MEDIA-LICENCE.md from the media manifest.
 *
 * Keeping the document generated rather than hand-written means the licence
 * record can never drift out of step with what is actually shipped — the same
 * data seeds `media_attributions` and drives the in-app /media page.
 *
 * Run: npm run media:attribution
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { MEDIA_ASSETS, MEDIA_GROUPS, allMediaPaths } from '../src/content/media/manifest';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

const lines: string[] = [
  '# Media licences and attribution',
  '',
  '> **Generated file.** Source: `src/content/media/manifest.ts`.',
  '> Regenerate with `npm run media:attribution`.',
  '',
  `Every one of the ${MEDIA_ASSETS.length} assets below (${allMediaPaths().length} files in total)`,
  'was created from scratch by this repository and is released under',
  '[CC0-1.0](https://creativecommons.org/publicdomain/zero/1.0/), a public domain',
  'dedication. You may use, modify and redistribute any of it for any purpose,',
  'including commercially, with no attribution required.',
  '',
  '## Why the licence position is unambiguous',
  '',
  'None of this is third-party work:',
  '',
  '- Raster scenes are rendered procedurally with Pillow from code in',
  '  `scripts/generate_media.py`. They are not photographs of real places or people.',
  '- Diagrams and icons are hand-authored SVG markup, written for this course.',
  '- Videos are encoded with ffmpeg from frames generated by the same script.',
  '- Audio is synthesised from mathematical expressions and contains no recording.',
  '',
  'Nothing is downloaded at build or run time, and nothing is hotlinked, so every',
  'lesson works offline.',
  '',
  '## Adding third-party media',
  '',
  'If you extend the library with assets you did not create:',
  '',
  '1. Verify the licence of **that individual file** — a site-wide licence',
  '   statement does not necessarily apply to every asset on the site.',
  '2. Download it into `public/learning-media/`; never hotlink.',
  '3. Record title, creator, source URL, licence, licence URL, the exact',
  '   attribution text required, the local path and the retrieval date.',
  '4. Add it to `MEDIA_ASSETS` and run `npm run media:verify`.',
  '',
  'Do not add anything whose licensing is unclear.',
  '',
];

for (const group of MEDIA_GROUPS) {
  const assets = MEDIA_ASSETS.filter((a) => group.slugs.includes(a.slug));
  if (assets.length === 0) continue;

  lines.push(`## ${group.label}`, '');
  lines.push('| Asset | Local path | Creator | Licence | Retrieved |');
  lines.push('|---|---|---|---|---|');

  for (const asset of assets) {
    const a = asset.attribution;
    lines.push(
      `| ${a.assetTitle} | \`${a.localPath}\` | ${a.creator} | ${a.licence} | ${a.retrievedOn} |`,
    );
  }
  lines.push('');
}

lines.push('## Full asset detail', '');
for (const asset of MEDIA_ASSETS) {
  const a = asset.attribution;
  lines.push(
    `### ${a.assetTitle}`,
    '',
    `- **Slug:** \`${asset.slug}\``,
    `- **Kind:** ${asset.kind}`,
    `- **Local path:** \`${a.localPath}\``,
    `- **Creator:** ${a.creator}`,
    `- **Source:** ${a.source}`,
    `- **Licence:** ${a.licence}${a.licenceUrl ? ` — ${a.licenceUrl}` : ''}`,
    `- **Attribution text:** ${a.attributionText}`,
    `- **Retrieved:** ${a.retrievedOn}`,
    ...(a.notes ? [`- **Notes:** ${a.notes}`] : []),
    ...(asset.suggestedAlt
      ? [`- **Suggested alt text:** ${asset.suggestedAlt}`]
      : ['- **Suggested alt text:** _(empty — this asset is the course\'s decorative example)_']),
    ...(asset.srcset.length > 0
      ? [`- **Responsive widths:** ${asset.srcset.map((s) => `${s.width}px`).join(', ')}`]
      : []),
    ...(asset.posterPath ? [`- **Poster:** \`${asset.posterPath}\``] : []),
    ...(asset.captionsPath ? [`- **Captions:** \`${asset.captionsPath}\``] : []),
    '',
  );
}

await writeFile(join(ROOT, 'MEDIA-LICENCE.md'), lines.join('\n'), 'utf8');
console.log(`✓ MEDIA-LICENCE.md written — ${MEDIA_ASSETS.length} assets documented`);
